repos:
- repo: local
  hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      # - id: end-of-file-fixer
      #   name: Fix End of Files
      #   entry: end-of-file-fixer
      #   language: system
      #   types: [text]
      #   stages: [commit, push, manual]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        args: []